"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api/client";
import { useAuth } from "@/context/auth-context";
import { FormField } from "@/types";
import { Brain, Plus, Trash2, Save, Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function AIBuilderPage() {
  const router = useRouter();
  const { user } = useAuth();
  const [prompt, setPrompt] = useState("");
  const [generating, setGenerating] = useState(false);
  const [formName, setFormName] = useState("");
  const [formDescription, setFormDescription] = useState("");
  const [fields, setFields] = useState<FormField[]>([]);
  const [saved, setSaved] = useState(false);

  const generateForm = async () => {
    if (!prompt.trim()) return;
    setGenerating(true);
    try {
      const result = await api.ai.generate(prompt);
      setFormName(result.name || "AI Generated Form");
      setFormDescription(result.description || "");
      setFields(result.fields || []);
      setSaved(false);
      toast.success("Form generated by AI!");
    } catch (err: any) { toast.error(err.message); }
    finally { setGenerating(false); }
  };

  const generateMore = async () => {
    setGenerating(true);
    try {
      const result = await api.ai.generate(`${prompt}\n\nAdd more fields to this form.`);
      setFields([...fields, ...(result.fields || [])]);
      toast.success("More fields added!");
    } catch (err: any) { toast.error(err.message); }
    finally { setGenerating(false); }
  };

  const saveForm = async () => {
    if (!formName || fields.length === 0) return;
    try {
      const form = await api.forms.create({ name: formName, slug: formName.toLowerCase().replace(/\s+/g, "-"), fields, description: formDescription, aiPrompt: prompt });
      setSaved(true);
      toast.success("Form saved!");
      router.push(`/forms/${form.id}`);
    } catch (err: any) { toast.error(err.message); }
  };

  const updateField = (index: number, key: string, value: any) => {
    setFields(fields.map((f, i) => i === index ? { ...f, [key]: value } : f));
  };

  const removeField = (index: number) => { setFields(fields.filter((_, i) => i !== index)); };
  const addField = () => { setFields([...fields, { name: `field_${fields.length + 1}`, label: "New Field", type: "text", required: false }]); };

  return (
    <div className="min-h-screen bg-muted/30">
      <header className="border-b bg-background"><div className="container flex h-16 items-center justify-between">
        <div className="flex items-center gap-3"><Brain className="h-6 w-6 text-primary"/><h1 className="text-xl font-bold">AI Form Builder</h1></div>
        <Button variant="ghost" onClick={() => router.push("/dashboard")}>Back to Dashboard</Button>
      </div></header>

      <main className="container py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left: Prompt */}
          <div className="space-y-6">
            <Card>
              <CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5"/> Describe Your Form</CardTitle></CardHeader>
              <CardContent className="space-y-4">
                <Textarea placeholder="e.g., Create a contact form with name, email, phone, and a message field. Make email required." value={prompt} onChange={e => setPrompt(e.target.value)} rows={6} />
                <Button onClick={generateForm} disabled={generating || !prompt.trim()} className="w-full">
                  {generating ? <><div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"/>Generating...</> : <><Brain className="h-4 w-4 mr-2"/>Generate Form</>}
                </Button>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle>Example Prompts</CardTitle></CardHeader>
              <CardContent className="space-y-2">
                {["Create a job application form with resume upload","Create an event registration form with payment","Create a customer feedback survey","Create a newsletter signup with preferences"].map(p => (
                  <button key={p} onClick={() => setPrompt(p)} className="w-full text-left text-sm p-2 rounded-md hover:bg-muted text-muted-foreground">{p}</button>
                ))}
              </CardContent>
            </Card>
          </div>

          {/* Right: Generated Form */}
          <div className="space-y-6">
            <Card>
              <CardHeader><CardTitle>Form Preview</CardTitle></CardHeader>
              <CardContent className="space-y-4">
                <Input value={formName} onChange={e => setFormName(e.target.value)} placeholder="Form Name" />
                <Textarea value={formDescription} onChange={e => setFormDescription(e.target.value)} placeholder="Description (optional)" rows={2} />
                {fields.length > 0 && (
                  <div className="space-y-3">
                    {fields.map((field, i) => (
                      <div key={i} className="flex items-center gap-2 p-3 border rounded-md">
                        <div className="flex-1 grid grid-cols-2 gap-2">
                          <Input value={field.label} onChange={e => updateField(i, "label", e.target.value)} placeholder="Label" className="text-sm" />
                          <select value={field.type} onChange={e => updateField(i, "type", e.target.value)} className="flex h-9 rounded-md border border-input bg-background px-2 text-sm">
                            {["text","email","number","textarea","select","radio","checkbox","date","phone"].map(t => <option key={t} value={t}>{t}</option>)}
                          </select>
                        </div>
                        <Badge variant={field.required?"default":"outline"} className="cursor-pointer" onClick={() => updateField(i, "required", !field.required)}>{field.required?"Required":"Optional"}</Badge>
                        <Button variant="ghost" size="sm" onClick={() => removeField(i)}><Trash2 className="h-3.5 w-3.5 text-destructive"/></Button>
                      </div>
                    ))}
                  </div>
                )}
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={addField}><Plus className="h-3.5 w-3.5 mr-1"/>Add Field</Button>
                  {fields.length > 0 && <Button variant="outline" size="sm" onClick={generateMore} disabled={generating}><Sparkles className="h-3.5 w-3.5 mr-1"/>Generate More</Button>}
                </div>
              </CardContent>
            </Card>

            {fields.length > 0 && (
              <Card>
                <CardHeader><CardTitle>Embed Code</CardTitle></CardHeader>
                <CardContent>
                  <pre className="bg-muted p-4 rounded-md text-xs overflow-x-auto font-mono">{`<form action="${process.env.NEXT_PUBLIC_APP_URL || "https://formflow.app"}/api/v1/submissions/${formName.toLowerCase().replace(/\s+/g, "-")}" method="POST">\n${fields.map(f => `  <input type="${f.type}" name="${f.name}" placeholder="${f.label}" ${f.required?"required":""} />`).join("\n")}\n  <button type="submit">Submit</button>\n</form>`}</pre>
                </CardContent>
              </Card>
            )}

            <Button onClick={saveForm} disabled={!formName || fields.length === 0 || saved} className="w-full">
              <Save className="h-4 w-4 mr-2"/>{saved ? "Form Saved!" : "Save Form"}
            </Button>
          </div>
        </div>
      </main>
    </div>
  );
}
